# .github/workflows/build-apk.yml
name: Build APK (hosted runner)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_API_LEVEL: "36"
      ANDROID_BUILD_TOOLS: "36.0.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AGP needs Java 17 even if your source targets Java 11
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Installs cmdline tools and puts sdkmanager/adb on PATH
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-${ANDROID_API_LEVEL}" \
                     "build-tools;${ANDROID_BUILD_TOOLS}"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew --no-daemon assembleRelease --stacktrace --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Attach APK to GitHub Release (when tagging)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
