name: Containerized Build (APK)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # e.g., v6.1

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
      ANDROID_API_LEVEL: "36"          # matches your project
      ANDROID_BUILD_TOOLS: "36.0.0"    # matches your project

    steps:
      - name: Install base packages
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git unzip ca-certificates wget tzdata

      - name: Checkout
        uses: actions/checkout@v4

      # AGP requires Java 17 to run the build (your source can stay Java 11)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Installs cmdline-tools + puts sdkmanager/adb on PATH for this job
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-${ANDROID_API_LEVEL}" \
                     "build-tools;${ANDROID_BUILD_TOOLS}"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew --no-daemon assembleRelease --stacktrace --info

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Attach APK to GitHub Release (when tagging)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
