name: Build APK (GitHub runner)

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'   # AGP needs JDK 17 to run

      - uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          set -eux
          yes | sdkmanager --licenses
          # Try stable first; if API 36 isn’t published there, fall back to preview channel
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0" || \
          (sdkmanager --channel=3 "platforms;android-36" && sdkmanager --channel=3 "build-tools;36.0.0")

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew --no-daemon assembleRelease --stacktrace --info

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
