name: Containerized Build (APK)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # if you push a tag like v6.1, it will attach the APK to that release

jobs:
  build:
    runs-on: ubuntu-latest

    # Keep the job containerized (meets “containerization” intent)
    container: ubuntu:22.04

    env:
      # Set the API level you want to install. If your build.gradle uses 36, keep 36 here.
      # If install fails later with "package not found", temporarily set this to 35
      # AND change compileSdk/targetSdk in build.gradle to 35 to match.
      ANDROID_API_LEVEL: "36"
      ANDROID_BUILD_TOOLS: "36.0.0"

    steps:
      - name: Install base packages
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git unzip ca-certificates wget tzdata

      - name: Checkout
        uses: actions/checkout@v4

      # AGP 8.x needs Java 17 to RUN the build (your source compatibility can still be Java 11)
      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Installs cmdline-tools and configures ANDROID_HOME / ANDROID_SDK_ROOT
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses
          echo "Installing platform-tools, platforms;android-${ANDROID_API_LEVEL}, build-tools;${ANDROID_BUILD_TOOLS}"
          sdkmanager \
            "platform-tools" \
            "platforms;android-${ANDROID_API_LEVEL}" \
            "build-tools;${ANDROID_BUILD_TOOLS}"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Helpful diagnostics
      - name: Show versions
        run: |
          java -version
          ./gradlew --version || true
          sdkmanager --list | head -n 200 || true

      - name: Build release APK
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      # Only runs on tag builds; won’t fail normal branch builds
      - name: Attach APK to GitHub Release (when tagging)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
